export enum AliCloudRegion {
    ChinaNorth1 = "cn-qingdao",
    ChinaNorth2 = "cn-beijing",
    ChinaNorth3 = "cn-zhangjiakou",
    ChinaNorth5 = "cn-huhehaote",
    ChinaEast1 = "cn-hangzhou",
    ChinaEast2 = "cn-shanghai",
    ChinaSouth1 = "cn-shenzhen",
    HongKong = "cn-hongkong",
    AsiaPacificSE1 = "ap-southeast-1",
    AsiaPacificSE2 = "ap-southeast-2",
    AsiaPacificSE3 = "ap-southeast-3",
    AsiaPacificSE5 = "ap-southeast-5",
    AsiaPacificNE1 = "ap-northeast-1",
    AsiaPacificSOU1 = "ap-south-1",
    USWest1 = "us-west-1",
    USEast1 = "us-east-1",
    Germany1 = "eu-central-1",
    MiddleEast1 = "me-east-1",
}
